// Regenerates src/lib/chain/votaloAbi.ts from the Foundry build output. Run after `forge build`.
import { readFileSync, writeFileSync } from "node:fs";

const artifact = JSON.parse(readFileSync("contracts/out/Votalo.sol/Votalo.json", "utf8"));
const body = JSON.stringify(artifact.abi, null, 2);
writeFileSync(
  "src/lib/chain/votaloAbi.ts",
  `// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit by hand.\nexport const votaloAbi = ${body} as const;\n`,
);
console.log("wrote src/lib/chain/votaloAbi.ts");
